version: "3"
services:
  mongodb:
    image: scrum-mongo:3.2.4
    container_name: "mongodb-scrum"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: docker-spring-mongo-scrum
    ports:
      - 8083:8083
    links:
      - mongodb-scrum